using Content.Shared._Stalker_EN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Loadout;

[GenerateTypedNameReferences]
public sealed partial class LoadoutItemControl : Control
{
    public PlayerLoadout Loadout { get; }

    public event Action<int>? OnLoadPressed;
    public event Action<int>? OnDeletePressed;

    private const int MaxNameLength = 24;

    public LoadoutItemControl(PlayerLoadout loadout)
    {
        RobustXamlLoader.Load(this);
        Loadout = loadout;

        var name = loadout.Name;
        if (name.Length > MaxNameLength)
            name = name[..MaxNameLength] + "..";

        // Style quick save differently
        if (loadout.Id == 0)
        {
            LoadoutName.Text = $"[Quick Save]";
            LoadoutName.FontColorOverride = Color.FromHex("#FFD700");
            if (Panel.PanelOverride is StyleBoxFlat styleBox)
            {
                styleBox.BackgroundColor = Color.FromHex("#2A2A00");
                styleBox.BorderColor = Color.FromHex("#5A5A00");
            }
        }
        else
        {
            LoadoutName.Text = name;
        }

        var itemCount = loadout.GetTotalItemCount();
        LoadoutInfo.Text = Loc.GetString("loadout-item-count", ("count", itemCount));

        if (loadout.MissingCount > 0)
        {
            MissingLabel.Text = Loc.GetString("loadout-missing-items", ("count", loadout.MissingCount));
            MissingLabel.Visible = true;
        }

        LoadButton.OnPressed += _ => OnLoadPressed?.Invoke(loadout.Id);
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(loadout.Id);
    }
}
