- type: entity
  parent: LocalTeleportBase
  id: LocalTeleportEcoBunker
  suffix: Ecologist
  name: Elevator Teleport
  components:
  - type: LinkByString
    linkString: EcoBunker

- type: entity
  parent: LocalTeleportBaseUncollide
  id: YantarLabLadderUncollide
  suffix: Yantar
  name: Yantar Lab Ladder Uncollide
  components:
  - type: LinkByString
    linkString: YantarLabLadder

