using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Radio;

/// <summary>
/// UI menu for the stalker radio headset.
/// Shows mic toggle and frequency input - no speaker toggle (speaker always active when equipped).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STRadioHeadsetMenu : FancyWindow
{
    public event Action<bool>? OnMicPressed;
    public event Action<string>? OnFrequencyEntered;

    public STRadioHeadsetMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MicButton.OnPressed += args =>
        {
            OnMicPressed?.Invoke(args.Button.Pressed);
        };

        FrequencyInput.OnTextEntered += args => OnFrequencyEntered?.Invoke(args.Text);
    }

    public void Update(STRadioHeadsetBoundUIState state)
    {
        MicButton.Pressed = state.MicEnabled;
        FrequencyInput.Text = state.CurrentFrequency ?? string.Empty;
    }
}
