using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Devices.ArtifactRadar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._Stalker_EN.Devices.ArtifactRadar;

[GenerateTypedNameReferences]
public sealed partial class ArtifactRadarWindow : FancyWindow
{
    // Color constants for button states (bright colors for visibility)
    private static readonly Color ButtonOnColor = Color.FromHex("#00FF00");   // Bright green
    private static readonly Color ButtonOffColor = Color.FromHex("#FF3030");  // Bright red

    public event Action? OnAnomalyDetectorToggle;
    public event Action? OnArtifactScannerToggle;

    public ArtifactRadarWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnomalyDetectorButton.OnPressed += _ => OnAnomalyDetectorToggle?.Invoke();
        ArtifactScannerButton.OnPressed += _ => OnArtifactScannerToggle?.Invoke();
    }

    /// <summary>
    /// Updates the window with the current artifact radar device state.
    /// </summary>
    public void UpdateState(ArtifactRadarBoundUIState state)
    {
        // Set header dynamically based on device name
        HeaderLabel.Text = Loc.GetString("artifact-radar-header-format", ("name", state.DeviceName.ToUpper()));

        // Artifact radar - always shown
        RadarControl.UpdateBlips(state.Blips, state.Range, state.ArtifactScannerEnabled);

        // Anomaly features - conditionally shown based on device capability
        AnomalyDetectorPanel.Visible = state.HasAnomalyDetector;
        WaveformPanel.Visible = state.HasAnomalyDetector;

        if (state.HasAnomalyDetector)
        {
            WaveformControl.UpdateState(state.AnomalyDetectorEnabled, state.ClosestAnomalyDistance);

            AnomalyDetectorStateLabel.Text = Loc.GetString(
                state.AnomalyDetectorEnabled ? "artifact-radar-state-on" : "artifact-radar-state-off");
            AnomalyDetectorStateLabel.FontColorOverride = state.AnomalyDetectorEnabled
                ? ButtonOnColor
                : ButtonOffColor;
        }

        // Artifact scanner - always shown
        ArtifactScannerStateLabel.Text = Loc.GetString(
            state.ArtifactScannerEnabled ? "artifact-radar-state-on" : "artifact-radar-state-off");
        ArtifactScannerStateLabel.FontColorOverride = state.ArtifactScannerEnabled
            ? ButtonOnColor
            : ButtonOffColor;
    }
}
