using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client.Message;
using Content.Shared.CartridgeLoader;
using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.PDA
{
    /// <summary>
    /// Client-side PDA menu with three views: Home, Settings, and Program content.
    /// Maintains a local cache of program items to avoid recreating UI controls on every state update,
    /// which prevents click loss when server updates arrive during user interaction.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        public const int HomeViewIndex = 0;
        public const int SettingsViewIndex = 1;
        public const int ProgramContentViewIndex = 2;

        [Dependency] private readonly IClipboardManager _clipboard = default!;
        [Dependency] private readonly IGameTiming _gameTiming = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
        private readonly ClientGameTicker _gameTicker;

        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");

        private int _currentView;

        /// <summary>
        /// Fired when the user requests deactivation of the current program (Home or Settings button).
        /// The BUI subscriber sends a Deactivate message to the server.
        /// </summary>
        public event Action? OnProgramDeactivated;

        /// <summary>
        /// Fired when the user selects a program from the program bar.
        /// The BUI subscriber sends an Activate message to the server.
        /// The server automatically deactivates any previously active program.
        /// </summary>
        public event Action<EntityUid>? OnProgramActivate;

        /// <summary>
        /// Fired when the user requests installation of a program cartridge.
        /// </summary>
        public event Action<EntityUid>? OnProgramInstall;

        /// <summary>
        /// Fired when the user requests uninstallation of a program.
        /// </summary>
        public event Action<EntityUid>? OnProgramUninstall;

        public PdaMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();

            // Add border to ProgramBar
            ProgramBarBorder.PanelOverride = new StyleBoxFlat
            {
                BorderColor = Color.FromHex("#5a5a5a"),
                BorderThickness = new Thickness(1),
                BackgroundColor = Color.FromHex("#1a1a1e"),
            };

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));

            HomeButton.OnPressed += _ => ToHomeScreen();
            SettingsButton.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;

                // Switch to settings view first, then deactivate program
                ChangeView(SettingsViewIndex);
                DeactivateActiveProgram();
            };
            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
            };
            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
            };
            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
            };
            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
            };
            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText(stationTime.ToString("hh\\:mm\\:ss"));
            };
            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
            };

            ToHomeScreen();
        }

        /// <summary>
        /// Applies server state to the UI. Does not change navigation state — that is handled
        /// separately by <see cref="SyncActiveProgram"/> and <see cref="OnServerProgramDeactivated"/>.
        /// </summary>
        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", _pdaOwner)));
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }

            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time-stalker", // stalker-en-changes - PDA UI
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertLevel = state.PdaOwnerInfo.StationAlertLevel;
            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            var alertLevelKey = alertLevel != null ? $"alert-level-{alertLevel}" : "alert-level-unknown";
            _alertLevel = Loc.GetString(alertLevelKey);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            _instructions = Loc.GetString($"{alertLevelKey}-instructions");
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;

            // stalker-changes-start - Update silent mode button text based on state
            SilentModeButton.Text = state.SilentModeEnabled
                ? Loc.GetString("comp-pda-ui-silent-mode-button-on")
                : Loc.GetString("comp-pda-ui-silent-mode-button-off");
            // stalker-changes-end

            // stalker-en-changes - PDA layout changes
            StalkerWeekLabel.SetMarkup(Loc.GetString("comp-pda-week-label", ("week", _gameTicker.RoundId)));
            // stalker-en-changes-end
        }

        private EntityUid? _activeProgram;

        /// <summary>
        /// Cache of program items by EntityUid. Items are reused on state updates
        /// to avoid recreating controls and losing click events.
        /// </summary>
        private readonly Dictionary<EntityUid, PdaProgramItem> _programItems = new();

        /// <summary>
        /// Synchronizes the local active program state with the server's authoritative state.
        /// Called from <see cref="PdaBoundUserInterface.UpdateState"/> on each state push.
        /// Updates the highlight on all program items.
        /// </summary>
        public void SyncActiveProgram(EntityUid? serverActiveProgram)
        {
            _activeProgram = serverActiveProgram;

            foreach (var (uid, item) in _programItems)
            {
                item.BackgroundColor = _activeProgram == uid
                    ? Color.FromHex("#316dca")
                    : Color.FromHex("#25252a");
            }
        }

        /// <summary>
        /// Updates the program bar with the available programs.
        /// Reuses existing items to avoid recreating controls, which prevents click loss
        /// when server updates arrive during user interaction.
        /// </summary>
        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            var remainingUids = new HashSet<EntityUid>(programs.Count);

            foreach (var (uid, component) in programs)
            {
                remainingUids.Add(uid);

                if (_programItems.TryGetValue(uid, out var item))
                    UpdateExistingItem(item, component, uid);
                else
                    CreateNewItem(component, uid);
            }

            RemoveStaleItems(remainingUids);
        }

        /// <summary>
        /// Updates an existing program item with new component data.
        /// Does not recreate the control — just updates text, icon, and buttons.
        /// </summary>
        private void UpdateExistingItem(PdaProgramItem item, CartridgeComponent component, EntityUid uid)
        {
            item.ProgramTitle = Loc.GetString(component.ProgramName);

            if (component.Icon is not null)
                item.Icon.SetFromSpriteSpecifier(component.Icon);

            UpdateInstallButton(item, component.InstallationStatus, uid);
            UpdateNotificationDot(item, component.HasNotification);
        }

        /// <summary>
        /// Creates a new program item, wires up event handlers, and adds it to the program bar.
        /// Events are wired once at creation time — update path uses the stored handler reference.
        /// </summary>
        private void CreateNewItem(CartridgeComponent component, EntityUid uid)
        {
            var item = new PdaProgramItem();
            item.ProgramTitle = Loc.GetString(component.ProgramName);

            if (component.Icon is not null)
                item.Icon.SetFromSpriteSpecifier(component.Icon);

            // Server manages deactivation of the previous program, so only Activate is needed.
            // No separate Deactivate message is sent when switching between programs.
            item.OnPressed += _ => OnProgramActivate?.Invoke(uid);

            UpdateInstallButton(item, component.InstallationStatus, uid);

            _programItems[uid] = item;
            ProgramBarContent.AddChild(item);
        }

        /// <summary>
        /// Updates the install/uninstall button text and handler based on the current installation status.
        /// Unsubscribes the previous handler before assigning a new one to avoid stale closures.
        /// </summary>
        private void UpdateInstallButton(PdaProgramItem item, InstallationStatus status, EntityUid uid)
        {
            item.InstallButton.OnPressed -= item.OnInstall;

            switch (status)
            {
                case InstallationStatus.Cartridge:
                    item.InstallButton.Visible = true;
                    item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                    item.OnInstall = _ => OnProgramInstall?.Invoke(uid);
                    item.InstallButton.OnPressed += item.OnInstall;
                    break;
                case InstallationStatus.Installed:
                    item.InstallButton.Visible = true;
                    item.InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                    item.OnInstall = _ => OnProgramUninstall?.Invoke(uid);
                    item.InstallButton.OnPressed += item.OnInstall;
                    break;
                default:
                    item.InstallButton.Visible = false;
                    item.OnInstall = null;
                    break;
            }
        }

        private void UpdateNotificationDot(PdaProgramItem item, bool hasNotification)
        {
            item.NotificationDot.Visible = hasNotification;
            if (hasNotification)
            {
                item.NotificationDot.PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#CC4444"),
                };
            }
        }

        /// <summary>
        /// Removes program items that no longer exist on the server.
        /// </summary>
        private void RemoveStaleItems(HashSet<EntityUid> remainingUids)
        {
            var toRemove = new List<EntityUid>();
            foreach (var (uid, item) in _programItems)
            {
                if (!remainingUids.Contains(uid))
                {
                    toRemove.Add(uid);
                    ProgramBarContent.RemoveChild(item);
                }
            }
            foreach (var uid in toRemove)
                _programItems.Remove(uid);
        }

        /// <summary>
        /// Switches to the Home view and deactivates the current program if one is active.
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            SettingsButton.IsCurrent = false;

            ChangeView(HomeViewIndex);
            DeactivateActiveProgram();
        }

        /// <summary>
        /// Deactivates the currently active program. Only fires <see cref="OnProgramDeactivated"/>
        /// if a program was actually active. Safe to call when no program is active.
        /// </summary>
        public void DeactivateActiveProgram()
        {
            if (_activeProgram.HasValue)
            {
                _activeProgram = null;
                OnProgramDeactivated?.Invoke();
            }
        }

        /// <summary>
        /// Switches to the Program view and deselects Home/Settings tabs.
        /// Called by the BUI when a cartridge UI fragment is attached.
        /// </summary>
        public void ToProgramView()
        {
            HomeButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;

            ChangeView(ProgramContentViewIndex);
        }

        /// <summary>
        /// Handles server-side program deactivation. If the user is currently viewing a program,
        /// returns to the Home screen. Safe to call even when no program was active.
        /// </summary>
        public void OnServerProgramDeactivated()
        {
            if (_currentView == ProgramContentViewIndex)
                ToHomeScreen();
        }


        /// <summary>
        /// Switches visibility of the three views based on the given view index.
        /// </summary>
        public void ChangeView(int view)
        {
            HomeView.Visible = view == HomeViewIndex;
            SettingsView.Visible = view == SettingsViewIndex;
            ProgramView.Visible = view == ProgramContentViewIndex;

            _currentView = view;
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time-stalker", // Stalker-en-changes - PDA UI
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
