using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    public const string NormalBgColor = "#313138";
    public const string HoverColor = "#3E6C45";

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex("#25252a"),
    };

    public string? ProgramTitle
    {
        get => ProgramName.Text;
        set => ProgramName.Text = value;
    }

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    /// <summary>
    /// Stores the current install button handler so it can be unsubscribed and rebound.
    /// </summary>
    public Action<ButtonEventArgs>? OnInstall;

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);

        // Resolve style once at construction instead of per-frame in Draw()
        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            _styleBox.BackgroundColor = bgColor;

        Panel.PanelOverride = _styleBox;

        // Set minimum size to ensure content fits
        MinSize = new Vector2(70, 60);

        // Ensure the item stretches to fill available space
        HorizontalExpand = true;
    }
}
