using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set => Background.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        const int resizeMargin = 10;
        var mode = DragMode.None;

        // Check for move (title bar area approximation)
        if (relativeMousePos.Y < 30 && relativeMousePos.X < Size.X - 40)
            mode |= DragMode.Move;

        // Check for resize handles
        if (relativeMousePos.X < resizeMargin)
            mode |= DragMode.Left;
        if (relativeMousePos.X > Size.X - resizeMargin)
            mode |= DragMode.Right;
        if (relativeMousePos.Y < resizeMargin)
            mode |= DragMode.Top;
        if (relativeMousePos.Y > Size.Y - resizeMargin)
            mode |= DragMode.Bottom;

        return mode;
    }
}
