using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Devices.Veles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Devices.Veles;

[GenerateTypedNameReferences]
public sealed partial class VelesWindow : FancyWindow
{
    public event Action? OnAnomalyDetectorToggle;
    public event Action? OnArtifactScannerToggle;

    public VelesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnomalyDetectorButton.OnPressed += _ => OnAnomalyDetectorToggle?.Invoke();
        ArtifactScannerButton.OnPressed += _ => OnArtifactScannerToggle?.Invoke();
    }

    public void UpdateState(VelesBoundUIState state)
    {
        RadarControl.UpdateBlips(state.Blips, state.Range);

        // Update button text to show current state
        AnomalyDetectorButton.Text = Loc.GetString(state.AnomalyDetectorEnabled
            ? "veles-button-anomaly-detector-on"
            : "veles-button-anomaly-detector-off");
        ArtifactScannerButton.Text = Loc.GetString(state.ArtifactScannerEnabled
            ? "veles-button-artifact-scanner-on"
            : "veles-button-artifact-scanner-off");
    }
}
