using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Devices.Veles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Stalker_EN.Devices.Veles;

[GenerateTypedNameReferences]
public sealed partial class VelesWindow : FancyWindow
{
    // Color constants for button states (bright colors for visibility)
    private static readonly Color ButtonOnColor = Color.FromHex("#00FF00");   // Bright green
    private static readonly Color ButtonOffColor = Color.FromHex("#FF3030");  // Bright red

    public event Action? OnAnomalyDetectorToggle;
    public event Action? OnArtifactScannerToggle;

    public VelesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnomalyDetectorButton.OnPressed += _ => OnAnomalyDetectorToggle?.Invoke();
        ArtifactScannerButton.OnPressed += _ => OnArtifactScannerToggle?.Invoke();
    }

    /// <summary>
    /// Updates the window with the current Veles device state.
    /// </summary>
    public void UpdateState(VelesBoundUIState state)
    {
        RadarControl.UpdateBlips(state.Blips, state.Range, state.ArtifactScannerEnabled);

        // Update waveform control (panel always visible, draws flat line when off)
        WaveformControl.UpdateState(state.AnomalyDetectorEnabled, state.ClosestAnomalyDistance);

        // Update state labels with colored ON/OFF text
        AnomalyDetectorStateLabel.Text = state.AnomalyDetectorEnabled ? "ON" : "OFF";
        AnomalyDetectorStateLabel.FontColorOverride = state.AnomalyDetectorEnabled
            ? ButtonOnColor
            : ButtonOffColor;

        ArtifactScannerStateLabel.Text = state.ArtifactScannerEnabled ? "ON" : "OFF";
        ArtifactScannerStateLabel.FontColorOverride = state.ArtifactScannerEnabled
            ? ButtonOnColor
            : ButtonOffColor;
    }
}
