- type: job
  id: StalkerClearSky
  name: Clear Sky Fighter
  icon: cn
  description: Looking for a way to coexist with the Zone.
  playTimeTracker: JobClearSky
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobClearSky
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerClearSkyGear
  supervisors: Explore the Zone and protect its secrets from prying eyes.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - CN
      - type: Bands
        band: Stalker
        altBand: stalker
        canChange: true
        bandIcon: cn
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: StalkerClearSkyGear
  equipment:
    id: ClearSkyPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatBomber
