- type: job
  id: StalkerZavet
  name: Covenant
  icon: zavet
  description: This is a small army of extremely dangerous fanatics.
  playTimeTracker: JobZavet
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobZavet
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerZavetGear
  supervisors: You are working for a Higher Power.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Covenant
        tags:
          - Covenant
          - Stalker
      - type: Bands
        band: Stalker
        bandIcon: zavet
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: StalkerZavetGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenantHead
    legs: ClothingLegsJeansBlackCargo
    shoes: ClothingShoesBootsWork

- type: startingGear
  id: StalkerZavetLeaderGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksCovenant
    legs: ClothingLegsJeansBrownCargo
    shoes: ClothingShoesBootsWork
