- type: job
  id: StalkerMercenary
  name: Mercenary
  icon: merc
  description: Adventurers and thugs from all over the world.
  playTimeTracker: JobStalkerMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerMercenaryGear
  supervisors: A well-planned operation with excellent preparation is the key to your success.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: StalkerHeadMercenary
  name: Head Mercenary
  icon: merc
  description: Your responsibility is to maintain communication with headquarters and directly make decisions on the contract.
  playTimeTracker: JobStalkerHeadMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerHeadMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerHeadMercenaryGear
  supervisors: you coordinate tactical operations, ensure effective communication between team members and make operational decisions on the battlefield
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadMerc
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerHeadMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
