- type: job
  id: StalkerScientist
  name: Scientist
  icon: sci
  description: The main goal is to study all aspects of the Zone, using scientific methods to further explain what the Zone is and its purpose.
  playTimeTracker: JobStalkerSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: You report to a senior employee and the Institute.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: sci
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: StalkerISSG
  name: SSGI operative
  icon: ecologists
  description: Fulfilling the orders of the institute is your everything.
  playTimeTracker: JobStalkerISSG
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: You report to a senior employee and the Institute.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: ecologists
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: StalkerHeadScientist
  name: Lead Scientist
  icon: sci
  description: The main goal is to study all aspects of the Zone, using scientific methods to further explain what the Zone is and its purpose.
  playTimeTracker: JobHeadStalkerSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: You report to a senior employee and the Institute.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - SciHead
        - type: Bands
          band: Stalker
          bandIcon: sci
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: SciGear
  equipment:
    id: ScientistPDA
    legs: ClothingLegsJeansSandCargo
    shoes: ClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific
