- type: job
  id: StalkerJaba
  name: Toad
  icon: jaba
  description: Group of special bandits
  playTimeTracker: JobJaba
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobJaba
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: JabaGear
  supervisors: You don't obey anyone...
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Jaba
      - type: Bands
        band: Stalker
        bandIcon: jaba
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: JabaGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoJaba
    legs: ClothingLegsJeansJaba
    shoes: ClothingShoesBootsFrogLeather
    gloves: ClothingHandsGlovesJabs
    mask: ClothingMaskSkull
    pocket1: GoldDiceBag
