- type: job
  id: StalkerTrader
  name: Trader
  icon: trader
  description: A group of merchants and hucksters from all over the Zone
  playTimeTracker: JobTrader
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobTrader
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: TraderGear
  supervisors: You work for yourself.
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Stalker
      - type: Bands
        band: Stalker
        bandIcon: trader
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: TraderGear
  equipment:
    id: StalkerPDA
    legs: ClothingLegsJeansSandCargo
    torso: ClothingTorsoTurtlenecksDeserterCamouflage
    shoes: ClothingShoesAerostatic
    belt: ClothingBeltMedicalStalker
    eyes: ClothingEyesGogglesAnomalist
    outerClothing: ClothingOuterCoatDetectiveDark
    neck: ClothingOuterCoatDetectiveDark
    gloves: ClothingHandsMercGlovesCombat
    head: ClothingHeadHatGreyFlatcap
