- type: entity
  id: CEZLevelLadderBase
  abstract: true
  categories: [ ForkFiltered ]
  parent: BaseStructure
  name: stairs
  description: Be careful, the higher you ascend, the more painful the fall.
  placement:
      mode: SnapgridCenter
      snap:
      - Wall
  components:
  - type: CEAutoTilePlacement
    tile: FloorStalker1
  - type: PlacementReplacement
    key: walls
  - type: Occluder
    boundingBox: "-0.5,0.25,0.5,0.5"
  - type: Sprite
    state: straight
    drawdepth: Mobs
  - type: Transform
    anchored: True
  - type: Clickable
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      hard:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,0.6,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        density: 1000
        hard: true
      slowdown:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.4,-0.4,0.4,0.4"
        layer:
          - SlipLayer
        mask:
          - ItemMask
        density: 1000
        hard: false
  - type: CEZLevelHighGround
    stick: true
    heightCurve:
    - 1.05
    - 1.05
    - 0.1
  - type: SpeedModifierContacts
    walkSpeedModifier: 0.3
    sprintSpeedModifier: 0.3

- type: entity
  parent: CEZLevelLadderBase
  id: CEZLevelLadderCornerBase
  abstract: true
  placement:
      mode: SnapgridCenter
      snap:
      - Wall
  components:
  - type: Sprite
    state: corner
  - type: Occluder
    enabled: false
  - type: CEZLevelHighGround
    corner: true
    heightCurve:
    - 1.05
    - 1.05
    - 0.5
    - 0.1
  - type: Fixtures
    fixtures:
      hard:
        shape:
          !type:PhysShapeAabb
          bounds: "0.5,0.5,0.6,0.6"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        density: 1000
        hard: true
      slowdown:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.4,-0.4,0.4,0.4"
        layer:
          - SlipLayer
        mask:
          - ItemMask
        density: 1000
        hard: false

- type: entity
  parent: CEZLevelLadderCornerBase
  id: CEZLevelLadderCornerInnerBase
  abstract: true
  placement:
      mode: SnapgridCenter
      snap:
      - Wall
  components:
  - type: Occluder
    enabled: true
    boundingBox: "-0.5,-0.5,0.5,0.5"
  - type: Sprite
    state: internal_corner
