using Content.Client.Message;
using Content.Client._Stalker_EN.UI.Controls;
using Content.Shared._Stalker_EN.News;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.News;

[GenerateTypedNameReferences]
public sealed partial class STNewsUiFragment : BoxContainer, INewsLinkClickHandler
{
    /// <summary>Fired when the journalist publishes an article.</summary>
    public event Action<string, string, int>? OnPublishArticle;

    /// <summary>Fired when the user requests full article content.</summary>
    public event Action<int>? OnRequestArticle;

    private readonly IClipboardManager _clipboard = IoCManager.Resolve<IClipboardManager>();

    private static readonly Color CardBackground = Color.FromHex("#1a1a2e");
    private static readonly Color CardBorder = Color.FromHex("#333355");
    private static readonly Color MetaColor = Color.FromHex("#888888");
    private static readonly Color PreviewColor = Color.FromHex("#AAAAAA");
    private static readonly Color NewIndicatorColor = Color.FromHex("#00CC00");

    private static string FormatNewsLink(int id) => $"[NEWS#{id}]";

    private static readonly (string Name, int Color)[] ColorPresets =
    {
        ("Red", 0xFF0000),
        ("Green", 0x00FF00),
        ("Blue", 0x0000FF),
        ("Yellow", 0xFFFF00),
        ("Orange", 0xFF8800),
        ("Purple", 0x8800FF),
        ("Teal", 0x00CCCC),
        ("White", 0xFFFFFF),
    };

    private int _selectedColor = ColorPresets[0].Color;

    /// <summary>ID of the article currently shown in the detail view, for the copy-link button.</summary>
    private int? _detailArticleId;

    /// <summary>Latest article summaries from server, cached for client-side filtering.</summary>
    private List<STNewsArticleSummary> _lastArticles = new();

    /// <summary>Latest new article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastNewIds = new();

    private readonly List<PanelContainer> _colorPanels = new();

    public STNewsUiFragment()
    {
        RobustXamlLoader.Load(this);

        HeaderLabel.Text = Loc.GetString("st-news-header");
        WriteButton.Text = Loc.GetString("st-news-write-button");
        NoArticlesLabel.Text = Loc.GetString("st-news-no-articles");
        BackButton.Text = Loc.GetString("st-news-back-button");
        WriterHeaderLabel.Text = Loc.GetString("st-news-writer-header");
        TitleLabel.Text = Loc.GetString("st-news-title-label");
        TitleEdit.PlaceHolder = Loc.GetString("st-news-title-placeholder");
        ContentLabel.Text = Loc.GetString("st-news-content-label");
        ContentEdit.Placeholder = new Rope.Leaf(Loc.GetString("st-news-content-placeholder"));
        EmbedColorLabel.Text = Loc.GetString("st-news-embed-color-label");
        CancelButton.Text = Loc.GetString("st-news-cancel-button");
        PreviewButton.Text = Loc.GetString("st-news-preview-button");
        PublishButton.Text = Loc.GetString("st-news-publish-button");
        PreviewHeaderLabel.Text = Loc.GetString("st-news-preview-header");
        PreviewCancelButton.Text = Loc.GetString("st-news-cancel-button");
        EditButton.Text = Loc.GetString("st-news-edit-button");
        PreviewPublishButton.Text = Loc.GetString("st-news-publish-button");

        DetailCopyLinkButton.Text = Loc.GetString("st-news-copy-link-button");

        WriteButton.OnPressed += _ => ShowWriter();
        BackButton.OnPressed += _ => ShowArticleList();
        DetailCopyLinkButton.OnPressed += _ =>
        {
            if (_detailArticleId is { } id)
                _clipboard.SetText(FormatNewsLink(id));
        };
        CancelButton.OnPressed += _ => ShowArticleList();
        PreviewButton.OnPressed += _ => ShowPreview();
        PublishButton.OnPressed += _ => DoPublish();
        PreviewCancelButton.OnPressed += _ => ShowWriter();
        EditButton.OnPressed += _ => ShowWriter();
        PreviewPublishButton.OnPressed += _ => DoPublish();

        TitleEdit.OnTextChanged += _ => UpdateTitleCounter();
        ContentEdit.OnTextChanged += _ => UpdateContentCounter();

        BuildColorPicker();
        UpdateTitleCounter();
        UpdateContentCounter();

        SearchBar.OnSearchTextChanged += _ => RebuildArticleList(_lastArticles, _lastNewIds);
    }

    /// <summary>Updates the fragment from the server-provided news UI state.</summary>
    public void UpdateState(STNewsUiState state)
    {
        WriteButton.Visible = state.CanWrite;

        if (state.OpenArticle != null)
        {
            ShowArticleDetail(state.OpenArticle);
            return;
        }

        if (state.OpenArticleId != null && state.OpenArticle == null)
            ShowArticleList();

        _lastArticles = state.Articles;
        _lastNewIds = state.NewArticleIds;
        RebuildArticleList(state.Articles, state.NewArticleIds);

        if (!WriterView.Visible && !PreviewView.Visible
            && !ArticleDetailView.Visible)
        {
            ShowArticleList();
        }
    }

    #region View Switching

    private void ShowArticleList()
    {
        ArticleListView.Visible = true;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = false;
    }

    private void ShowArticleDetail(STNewsArticle article)
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = true;
        WriterView.Visible = false;
        PreviewView.Visible = false;

        _detailArticleId = article.Id;
        DetailTitle.Text = article.Title;
        DetailAuthor.Text = Loc.GetString(
            "st-news-detail-author", ("author", article.Author));
        DetailMeta.Text = Loc.GetString(
            "st-news-detail-meta",
            ("round", article.RoundId),
            ("time", article.PublishTime.ToString(@"hh\:mm\:ss")));
        DetailContent.SetMarkupPermissive(article.Content);
    }

    private void ShowWriter()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = true;
        PreviewView.Visible = false;
        UpdateTitleCounter();
        UpdateContentCounter();
    }

    private void ShowPreview()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = true;

        PreviewTitle.Text = TitleEdit.Text;
        PreviewContent.SetMarkupPermissive(
            Rope.Collapse(ContentEdit.TextRope));
    }

    #endregion

    #region Article List

    private void RebuildArticleList(List<STNewsArticleSummary> articles, HashSet<int> newArticleIds)
    {
        ArticleList.RemoveAllChildren();

        var query = SearchBar.SearchText;
        var hasResults = false;

        foreach (var article in articles)
        {
            if (!STSearchFilter.Matches(query, article.Title, article.Author)
                && !STSearchFilter.Matches(query, article.Preview))
            {
                continue;
            }

            var isNew = newArticleIds.Contains(article.Id);
            ArticleList.AddChild(BuildArticleCard(article, isNew));
            hasResults = true;
        }

        NoArticlesLabel.Visible = !hasResults;
        ArticleScroll.Visible = hasResults;
    }

    private Control BuildArticleCard(STNewsArticleSummary article, bool isNew)
    {
        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardBackground,
                ContentMarginLeftOverride = 0,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
                BorderColor = CardBorder,
                BorderThickness = new Thickness(0, 0, 0, 1),
            },
            HorizontalExpand = true,
            Margin = new Thickness(4, 2, 4, 2),
        };

        // Colored left border strip using the article's embed color
        var colorStrip = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex($"#{article.EmbedColor:X6}"),
            },
            MinWidth = 4,
            MaxWidth = 4,
            VerticalExpand = true,
        };

        var vbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(8, 0, 0, 0),
        };

        var titleRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        if (isNew)
        {
            var newLabel = new Label
            {
                Text = Loc.GetString("st-news-new-indicator"),
                FontColorOverride = NewIndicatorColor,
                Margin = new Thickness(0, 0, 6, 0),
            };
            titleRow.AddChild(newLabel);
        }

        var titleLabel = new Label
        {
            Text = article.Title,
            StyleClasses = { "LabelHeading" },
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            ClipText = false,
        };
        titleRow.AddChild(titleLabel);
        vbox.AddChild(titleRow);

        var metaLabel = new Label
        {
            Text = Loc.GetString("st-news-card-meta",
                ("author", article.Author),
                ("round", article.RoundId),
                ("time", article.PublishTime.ToString(@"hh\:mm\:ss"))),
            FontColorOverride = MetaColor,
        };
        vbox.AddChild(metaLabel);

        if (!string.IsNullOrEmpty(article.Preview))
        {
            var previewLabel = new Label
            {
                Text = article.Preview,
                FontColorOverride = PreviewColor,
                HorizontalExpand = true,
                ClipText = false,
            };
            vbox.AddChild(previewLabel);
        }

        var buttonRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Right,
            SeparationOverride = 4,
            Margin = new Thickness(0, 4, 0, 0),
        };

        var articleId = article.Id;

        var copyButton = new Button
        {
            Text = Loc.GetString("st-news-copy-link-button"),
        };
        copyButton.OnPressed += _ =>
            _clipboard.SetText(FormatNewsLink(articleId));
        buttonRow.AddChild(copyButton);

        var readButton = new Button
        {
            Text = Loc.GetString("st-news-read-button"),
        };
        readButton.OnPressed += _ => OnRequestArticle?.Invoke(articleId);
        buttonRow.AddChild(readButton);

        vbox.AddChild(buttonRow);

        var hbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        hbox.AddChild(colorStrip);
        hbox.AddChild(vbox);

        card.AddChild(hbox);
        return card;
    }

    #endregion

    #region Writer

    private void BuildColorPicker()
    {
        foreach (var (name, color) in ColorPresets)
        {
            var panel = new PanelContainer
            {
                MinSize = new System.Numerics.Vector2(24, 24),
                MaxSize = new System.Numerics.Vector2(24, 24),
                ToolTip = name,
                MouseFilter = MouseFilterMode.Stop,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex($"#{color:X6}"),
                    BorderColor = Color.Transparent,
                    BorderThickness = new Thickness(2),
                },
            };

            var colorValue = color;
            var panelRef = panel;
            panel.OnKeyBindDown += args =>
            {
                if (args.Function != Robust.Shared.Input.EngineKeyFunctions.UIClick)
                    return;

                _selectedColor = colorValue;
                UpdateColorSelection(panelRef);
            };

            _colorPanels.Add(panel);
            ColorPicker.AddChild(panel);
        }

        UpdateColorSelection(_colorPanels[0]);
    }

    private void UpdateColorSelection(PanelContainer? selected)
    {
        foreach (var panel in _colorPanels)
        {
            if (panel.PanelOverride is StyleBoxFlat flat)
                flat.BorderColor = panel == selected ? Color.White : Color.Transparent;
        }
    }

    private void DoPublish()
    {
        var title = TitleEdit.Text.Trim();
        var content = Rope.Collapse(ContentEdit.TextRope).Trim();

        if (string.IsNullOrEmpty(title) || string.IsNullOrEmpty(content))
            return;

        OnPublishArticle?.Invoke(title, content, _selectedColor);

        TitleEdit.Text = string.Empty;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        _selectedColor = ColorPresets[0].Color;
        UpdateColorSelection(_colorPanels[0]);

        ShowArticleList();
    }

    private void UpdateTitleCounter()
    {
        var remaining = STNewsConstants.MaxTitleLength - TitleEdit.Text.Length;
        TitleCounter.Text = $"{remaining}/{STNewsConstants.MaxTitleLength}";
        TitleCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    private void UpdateContentCounter()
    {
        var len = (int) Rope.CalcTotalLength(ContentEdit.TextRope);
        var remaining = STNewsConstants.MaxContentLength - len;
        ContentCounter.Text = $"{remaining}/{STNewsConstants.MaxContentLength}";
        ContentCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    #endregion

    #region News Link Handler

    public void HandleNewsLinkClick(int articleId)
    {
        OnRequestArticle?.Invoke(articleId);
    }

    #endregion
}
