using Content.Shared._Stalker.CCCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Stalker.PdaMessenger;

[GenerateTypedNameReferences]
public sealed partial class PdaNotificationPanel : PanelContainer
{
    private static readonly ISawmill Sawmill = Logger.GetSawmill("pda.notifications");
    private readonly IConfigurationManager _configManager;
    private readonly string? _bandId;
    private bool _usePngIcons;

    public PdaNotificationPanel(string title, string content, string sender, string? bandId = null)
    {
        RobustXamlLoader.Load(this);

        _configManager = IoCManager.Resolve<IConfigurationManager>();
        _bandId = bandId;

        // Subscribe to CVar changes
        _configManager.OnValueChanged(CCCCVars.PdaNotificationPngIcons, OnPngIconsChanged, invokeImmediately: true);

        TitleLabel.Text = title;
        ContentLabel.SetMessage(FormattedMessage.FromMarkup(content));

        // Display faction icon based on current setting
        UpdateFactionIcon();

        // Panel style - transparent background
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
        };
    }

    private void OnPngIconsChanged(bool newValue)
    {
        _usePngIcons = newValue;
        UpdateFactionIcon();
    }

    private void UpdateFactionIcon()
    {
        if (_usePngIcons)
        {
            // PNG icon mode - map bandIcon to texture path (always returns a path, even for unknown)
            var texturePath = GetTexturePathForBandIcon(_bandId);

            try
            {
                var resourceCache = IoCManager.Resolve<IResourceCache>();
                if (resourceCache.TryGetResource<TextureResource>(texturePath, out var texture))
                {
                    FactionIcon.Texture = texture;
                    FactionIcon.Visible = true;
                }
                else
                {
                    // Failed to load texture - hide icon
                    FactionIcon.Visible = false;
                }
            }
            catch
            {
                FactionIcon.Visible = false;
            }
        }
        else
        {
            // Sprite icon mode - use RSI sprite from band.rsi (same as STMessenger)
            var spriteState = GetSpriteStateForBandIcon(_bandId ?? string.Empty);
            if (spriteState is null)
            {
                FactionIcon.Visible = false;
                return;
            }

            try
            {
                var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
                var specifier = new SpriteSpecifier.Rsi(new("/Textures/_Stalker/Icons/Patches/band.rsi"), spriteState);
                var texture = spriteSystem.Frame0(specifier);
                FactionIcon.Texture = texture;
                FactionIcon.Visible = true;
            }
            catch
            {
                FactionIcon.Visible = false;
            }
        }
    }

    /// <summary>
    /// Maps bandIcon name to RSI sprite state name.
    /// </summary>
    private static string? GetSpriteStateForBandIcon(string bandIcon)
    {
        return bandIcon switch
        {
            // Major factions
            "freedom" => "freedom",
            "Dolg" => "dolg",
            "band" => "band",
            "rene" => "rene",
            "monolith" => "monolith",
            "cn" => "cn",
            "stalker" => "stalker",
            "merc" => "merc",
            "army" => "army",
            "voen" => "voen",
            "sci" => "sci",
            "sci_decan" => "sci_decan",
            "sci_rector" => "sci_rector",

            // Minor factions
            "militia" => "militia",
            "ecologists" => "ecologist",
            "ecologistred" => "ecologist_red",
            "seraphim" => "seraph",
            "zavet" => "zavet",
            "greh" => "greh",
            "sbu" => "sbu",
            "un" => "un",
            "project-1" => "project-1",
            "trader" => "trader",
            "clowns" => "clowns",
            "jaba" => "jaba",
            "pilgrim" => "pilgrim",
            "guide" => "guide",
            "pack" => "pack",
            "symbiote" => "symbiote",
            "medbeysprite" => "med",
            "grajdansksprite" => "ne",

            _ => null // Unknown icon
        };
    }

    /// <summary>
    /// Maps bandIcon name to PNG texture path.
    /// Returns NoData.png if bandIcon is unknown.
    /// </summary>
    private static ResPath GetTexturePathForBandIcon(string? bandIcon)
    {
        if (string.IsNullOrEmpty(bandIcon))
            return new ResPath("/Textures/_Stalker_EN/Factions/NoData.png");

        return bandIcon switch
        {
            // Major factions
            "freedom" => new ResPath("/Textures/_Stalker_EN/Factions/STFreedomBand.png"),
            "Dolg" => new ResPath("/Textures/_Stalker_EN/Factions/STDolgBand.png"),
            "band" => new ResPath("/Textures/_Stalker_EN/Factions/STBanditsBand.png"),
            "rene" => new ResPath("/Textures/_Stalker_EN/Factions/STRenegatsBand.png"),
            "monolith" => new ResPath("/Textures/_Stalker_EN/Factions/STMonolithBand.png"),
            "cn" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "stalker" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "merc" => new ResPath("/Textures/_Stalker_EN/Factions/STMercenariesBand.png"),
            "army" => new ResPath("/Textures/_Stalker_EN/Factions/STMilitaryBand.png"),
            "voen" => new ResPath("/Textures/_Stalker_EN/Factions/STMilitaryBand.png"),
            "sci" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),
            "sci_decan" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),
            "sci_rector" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),

            // Minor factions - map to closest available texture
            "militia" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "ecologists" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),
            "ecologistred" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),
            "seraphim" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "zavet" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "greh" => new ResPath("/Textures/_Stalker_EN/Factions/STRenegatsBand.png"),
            "sbu" => new ResPath("/Textures/_Stalker_EN/Factions/STMilitaryBand.png"),
            "un" => new ResPath("/Textures/_Stalker_EN/Factions/STNeutralBand.png"),
            "project-1" => new ResPath("/Textures/_Stalker_EN/Factions/STNeutralBand.png"),
            "trader" => new ResPath("/Textures/_Stalker_EN/Factions/STNeutralBand.png"),
            "clowns" => new ResPath("/Textures/_Stalker_EN/Factions/STNeutralBand.png"),
            "jaba" => new ResPath("/Textures/_Stalker_EN/Factions/STBanditsBand.png"),
            "pilgrim" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "guide" => new ResPath("/Textures/_Stalker_EN/Factions/STStalkerBand.png"),
            "pack" => new ResPath("/Textures/_Stalker_EN/Factions/STRenegatsBand.png"),
            "symbiote" => new ResPath("/Textures/_Stalker_EN/Factions/STRenegatsBand.png"),
            "medbeysprite" => new ResPath("/Textures/_Stalker_EN/Factions/STSciBand.png"),
            "grajdansksprite" => new ResPath("/Textures/_Stalker_EN/Factions/STNeutralBand.png"),

            // Unknown faction - use NoData placeholder
            _ => new ResPath("/Textures/_Stalker_EN/Factions/NoData.png")
        };
    }

    /// <summary>
    /// Sets the transparency of the notification content (text + icon), but not the background.
    /// Alpha: 1.0 = fully opaque, 0.0 = fully transparent
    /// </summary>
    public void SetAlpha(float alpha)
    {
        var clampedAlpha = MathHelper.Clamp(alpha, 0f, 1f);
        var modulate = Color.White.WithAlpha(clampedAlpha);

        // Apply to all children iteratively (avoids recursion)
        var stack = new Stack<Control>();
        stack.Push(this);

        while (stack.Count > 0)
        {
            var control = stack.Pop();
            control.ModulateSelfOverride = modulate;

            foreach (var child in control.Children)
            {
                if (child is Control childControl)
                    stack.Push(childControl);
            }
        }
    }

    /// <summary>
    /// Called when the panel is disposed.
    /// </summary>
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            // Unsubscribe from CVar changes to prevent memory leaks
            _configManager.UnsubValueChanged(CCCCVars.PdaNotificationPngIcons, OnPngIconsChanged);
        }
    }
}
