using Content.Client._Stalker_EN.FactionRelations;
using Content.Client._Stalker_EN.UI;
using Content.Shared._Stalker.CCCCVars;
using Content.Shared._Stalker_EN.Leaderboard;
using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._Stalker_EN.Leaderboard;

[GenerateTypedNameReferences]
public sealed partial class STLeaderboardUiFragment : BoxContainer
{
    private SpriteSystem? _spriteSystem;
    private IConfigurationManager? _cfg;
    private IPrototypeManager? _proto;
    private bool _usePngIcons;
    private List<STLeaderboardEntry>? _currentEntries;
    private BoundUserInterface? _boundUserInterface;

    private SpriteSystem SpriteSystem => _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
    private IConfigurationManager Cfg => _cfg ??= IoCManager.Resolve<IConfigurationManager>();
    private IPrototypeManager Proto => _proto ??= IoCManager.Resolve<IPrototypeManager>();

    public STLeaderboardUiFragment()
    {
        RobustXamlLoader.Load(this);

        // Subscribe to CVar changes for portrait/patch switching (same as PDA notification)
        Cfg.OnValueChanged(CCCCVars.PdaNotificationPngIcons, OnPngIconsChanged, invokeImmediately: true);

        // Subscribe to checkbox toggle event
        HiddenCheckBox.OnToggled += OnHiddenCheckBoxToggled;
    }

    public void SetBoundUserInterface(BoundUserInterface bui)
    {
        _boundUserInterface = bui;
    }

    private void OnHiddenCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_boundUserInterface != null)
        {
            var message = new CartridgeUiMessage(new STLeaderboardToggleHiddenMessage());
            _boundUserInterface.SendMessage(message);
        }
    }

    private void OnPngIconsChanged(bool newValue)
    {
        _usePngIcons = newValue;
        // Re-render all entries with new setting
        if (_currentEntries != null)
            UpdateState(_currentEntries);
    }

    public void UpdateState(List<STLeaderboardEntry> entries)
    {
        _currentEntries = entries;
        EntriesList.RemoveAllChildren();

        STLeaderboardEntry? myEntry = null;
        var myPosition = -1;
        var position = 1;

        foreach (var entry in entries)
        {
            var row = _makeEntry(position, entry);
            EntriesList.AddChild(row);

            if (entry.IsMe)
            {
                myEntry = entry;
                myPosition = position;
            }

            position++;
        }

        // Show pinned entry below the scroll area — always visible, same position as in list
        PinnedContainer.Visible = myEntry.HasValue;
        PinnedEntry.RemoveAllChildren();
        if (myEntry.HasValue && myPosition > 0)
        {
            var pinnedRow = _makeEntry(myPosition, myEntry.Value);
            PinnedEntry.AddChild(pinnedRow);

            // Update checkbox state based on hidden status
            HiddenCheckBox.Pressed = myEntry.Value.Hidden;
        }
    }

    private Control _makeEntry(int position, STLeaderboardEntry entry)
    {
        var container = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 4),
            HorizontalExpand = true,
        };

        var iconPanel = new PanelContainer
        {
            MinSize = new Vector2(80, 80),
            Margin = new Thickness(0, 0, 8, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
            },
        };

        iconPanel.AddChild(_getPortraitOrPatchTexture(entry));
        container.AddChild(iconPanel);

        var infoBlock = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true,
        };

        var nameLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var nameMsg = new FormattedMessage();
        var displayName = string.IsNullOrEmpty(entry.CharacterName) ? Loc.GetString("st-leaderboard-nodata") : entry.CharacterName;
        nameMsg.AddMarkupOrThrow($"[b]{position}. {FormattedMessage.EscapeText(displayName)}[/b]");
        nameLine.SetMessage(nameMsg);
        infoBlock.AddChild(nameLine);

        var factionDisplay = entry.DisplayBandName ?? Loc.GetString("st-leaderboard-nodata");
        var factionColor = _getRelationColor(entry.BandRelation);
        var factionLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var factionMsg = new FormattedMessage();
        factionMsg.PushColor(factionColor);
        factionMsg.AddText($"{Loc.GetString("st-leaderboard-faction-label")} {factionDisplay}");
        factionMsg.Pop();
        factionLine.SetMessage(factionMsg);
        infoBlock.AddChild(factionLine);

        var rankDisplay = entry.RankName != null ? Loc.GetString(entry.RankName) : Loc.GetString("st-leaderboard-nodata");
        var rankLine = new RichTextLabel { HorizontalExpand = true };
        var rankMsg = new FormattedMessage();
        rankMsg.AddText($"{Loc.GetString("st-leaderboard-rank-label")} {rankDisplay}");
        rankLine.SetMessage(rankMsg);
        infoBlock.AddChild(rankLine);

        container.AddChild(infoBlock);
        return container;
    }

    private static Color _getRelationColor(STLeaderboardFactionRelation relation) => relation switch
    {
        STLeaderboardFactionRelation.Same => Color.FromHex("#FFFFFF"),
        STLeaderboardFactionRelation.Alliance => Color.FromHex("#33CC33"),
        STLeaderboardFactionRelation.Neutral => Color.FromHex("#FFD700"),
        STLeaderboardFactionRelation.Hostile => Color.FromHex("#FF8800"),
        STLeaderboardFactionRelation.War => Color.FromHex("#FF4444"),
        _ => Color.FromHex("#CCCCCC"),
    };

    private static readonly ResPath LeaderboardRsiPath = new("/Textures/_Stalker_EN/Interface/Cartridges/leaderboard.rsi");

    private Control _getPortraitOrPatchTexture(STLeaderboardEntry entry)
    {
        var fallbackTexture = SpriteSystem.Frame0(new SpriteSpecifier.Rsi(LeaderboardRsiPath, "nodata"));

        return PortraitIconHelper.CreatePortraitOrPatchRect(
            entry.PortraitPath,
            entry.BandIcon,
            _usePngIcons,
            new Vector2(80, 80),
            fallbackTexture);
    }
}
