using Content.Shared._Stalker.CCCCVars;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

[GenerateTypedNameReferences]
public sealed partial class PdaNotificationPanel : PanelContainer
{
    private static readonly ISawmill Sawmill = Logger.GetSawmill("pda.notifications");
    private readonly IConfigurationManager _configManager;
    private readonly string? _bandIcon;
    private readonly string? _portraitId;
    private readonly bool _isDisguised;
    private bool _usePngIcons;

    public PdaNotificationPanel(string title, string content, string? bandIcon = null, string? portraitId = null, bool isDisguised = false)
    {
        RobustXamlLoader.Load(this);

        _configManager = IoCManager.Resolve<IConfigurationManager>();
        _bandIcon = bandIcon;
        _portraitId = portraitId;
        _isDisguised = isDisguised;

        // Subscribe to CVar changes
        _configManager.OnValueChanged(CCCCVars.PdaNotificationPngIcons, OnPngIconsChanged, invokeImmediately: true);

        TitleLabel.Text = title;
        ContentLabel.SetMessage(FormattedMessage.FromMarkup(content));

        // Display icon based on settings
        UpdateFactionIcon();

        // Panel style - transparent background
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
        };
    }

    private void OnPngIconsChanged(bool newValue)
    {
        _usePngIcons = newValue;
        UpdateFactionIcon();
    }

    private void UpdateFactionIcon()
    {
        // When _usePngIcons is true — use character portrait if available
        if (_usePngIcons && !string.IsNullOrEmpty(_portraitId))
        {
            try
            {
                var resourceCache = IoCManager.Resolve<IResourceCache>();
                var texturePath = _portraitId;

                if (resourceCache.TryGetResource<TextureResource>(texturePath, out var texture))
                {
                    FactionIcon.Texture = texture;
                    FactionIcon.Visible = true;
                }
            }
            catch
            {
                // Fall through to band icon
            }
        }
        else
        {
            // Sprite icon mode - use JobIconPrototype system
            if (!string.IsNullOrEmpty(_bandIcon))
            {
                try
                {
                    var protoManager = IoCManager.Resolve<IPrototypeManager>();
                    var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

                    if (protoManager.TryIndex<JobIconPrototype>(_bandIcon, out var iconProto))
                    {
                        var texture = spriteSystem.Frame0(iconProto.Icon);
                        FactionIcon.Texture = texture;
                        FactionIcon.Visible = true;
                    }
                    else
                    {
                        FactionIcon.Visible = false;
                    }
                }
                catch
                {
                    FactionIcon.Visible = false;
                }
            }
            else
            {
                FactionIcon.Visible = false;
            }
        }
    }


    /// <summary>
    /// Sets the transparency of the notification content (text + icon), but not the background.
    /// Alpha: 1.0 = fully opaque, 0.0 = fully transparent
    /// </summary>
    public void SetAlpha(float alpha)
    {
        var clampedAlpha = MathHelper.Clamp(alpha, 0f, 1f);
        var modulate = Color.White.WithAlpha(clampedAlpha);

        // Apply to all children iteratively (avoids recursion)
        var stack = new Stack<Control>();
        stack.Push(this);

        while (stack.Count > 0)
        {
            var control = stack.Pop();
            control.ModulateSelfOverride = modulate;

            foreach (var child in control.Children)
            {
                if (child is Control childControl)
                    stack.Push(childControl);
            }
        }
    }

    /// <summary>
    /// Called when the panel is disposed.
    /// </summary>
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            // Unsubscribe from CVar changes to prevent memory leaks
            _configManager.UnsubValueChanged(CCCCVars.PdaNotificationPngIcons, OnPngIconsChanged);
        }
    }
}
