using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker_EN.Devices.Radar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._Stalker_EN.Devices.Radar.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarWindow : FancyWindow
{
    // Color constants for button states (bright colors for visibility)
    private static readonly Color ButtonOnColor = Color.FromHex("#00FF00");   // Bright green
    private static readonly Color ButtonOffColor = Color.FromHex("#FF3030");  // Bright red

    public event Action? OnAnomalyDetectorToggle;
    public event Action? OnRadarToggle;

    public RadarWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnomalyDetectorButton.OnPressed += _ => OnAnomalyDetectorToggle?.Invoke();
        RadarButton.OnPressed += _ => OnRadarToggle?.Invoke();
    }

    /// <summary>
    /// Updates the window with the current radar device state.
    /// </summary>
    public void UpdateState(RadarDisplayBoundUIState state)
    {
        // Set header dynamically based on device name
        HeaderLabel.Text = Loc.GetString("artifact-radar-header-format", ("name", state.DeviceName.ToUpper()));

        // Radar - always shown
        RadarControl.UpdateBlips(state.Blips, state.Range, state.RadarEnabled);

        // Capability indicators - show what the device can detect
        ArtifactIndicator.Visible = state.HasArtifactDetection;
        AnomalyIndicator.Visible = state.HasAnomalyDetection;
        // Show separator only when both capabilities are present
        SeparatorLabel.Visible = state.HasArtifactDetection && state.HasAnomalyDetection;

        // Anomaly features - conditionally shown based on device capability
        AnomalyDetectorPanel.Visible = state.HasAnomalyDetector;
        WaveformPanel.Visible = state.HasAnomalyDetector;

        if (state.HasAnomalyDetector)
        {
            WaveformControl.UpdateState(state.AnomalyDetectorEnabled, state.ClosestAnomalyDistance);

            AnomalyDetectorStateLabel.Text = Loc.GetString(
                state.AnomalyDetectorEnabled ? "artifact-radar-state-on" : "artifact-radar-state-off");
            AnomalyDetectorStateLabel.FontColorOverride = state.AnomalyDetectorEnabled
                ? ButtonOnColor
                : ButtonOffColor;
        }

        // Radar - always shown
        RadarStateLabel.Text = Loc.GetString(
            state.RadarEnabled ? "artifact-radar-state-on" : "artifact-radar-state-off");
        RadarStateLabel.FontColorOverride = state.RadarEnabled
            ? ButtonOnColor
            : ButtonOffColor;
    }
}
